main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  # Recipes Routes
  path('recipes/', views.recipes_index, name='recipes_index'),
  path('recipes/<int:recipe_id>/', views.recipes_detail, name='recipes_detail'),
  path('recipes/create/', views.RecipeCreate.as_view(), name='recipes_create'),
  path('recipes/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipes_update'),
  path('recipes/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipes_delete'),
  path('recipes/<int:recipe_id>/add_instruction/', views.add_instruction, name='add_instruction'),
  path('recipes/<int:recipe_id>/assoc_ing/<int:ingredient_id>/', views.assoc_ing, name='assoc_ing'),
  # Ingredients Routes
  path('ingredients/', views.IngredientList.as_view(), name='ingredients_index'),
  path('ingredients/<int:pk>/', views.IngredientDetail.as_view(), name='ingredients_detail'),
  path('ingredients/create/', views.IngredientCreate.as_view(), name='ingredients_create'),
  path('ingredients/<int:pk>/update/', views.IngredientUpdate.as_view(), name='ingredients_update'),
  path('ingredients/<int:pk>/delete/', views.IngredientDelete.as_view(), name='ingredients_delete'),
  # Signup Route
  path('accounts/signup/', views.signup, name='signup'),
]

recipecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

INGREDIENT_TYPE = (('MI', 'Miscellaneous'), ('FR', 'Fruit'), ('VG', 'Vegetable'), ('SP', 'Spice'), ('HE', 'Herb'), ('DY', 'Dairy'), ('CH', 'Poultry'), ('BF', 'Beef'), ('CH', 'Cheese'), ('FU', 'Mushroom'), ('OI', 'Oil'), ('FL', 'Flour'), ('PE', 'Peanut'), ('NU', 'Tree Nut'))

# Create your models here.
class Ingredient(models.Model):
  name = models.CharField(max_length=50)
  category = models.CharField(max_length=2, choices=INGREDIENT_TYPE, default=INGREDIENT_TYPE[0][0])
  
  def __str__(self):
    return f'{self.name} is of type {self.category}'
  
  def get_absolute_url(self):
    return reverse('ingredients_detail', kwargs={'pk': self.id})

class Recipe(models.Model):
  name = models.CharField(max_length=100)
  cuisine = models.CharField(max_length=50)
  description = models.CharField(max_length=250)
  
  ingredients = models.ManyToManyField(Ingredient)
  
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
    return reverse('recipes_detail', kwargs={'recipe_id': self.id})
  
class Instruction(models.Model):
  step_no = models.IntegerField()
  description = models.CharField(max_length=250)
  
  recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
  
  def __str__(self):
    return f'Step {step_no}: {description}'
  
  class Meta:
    ordering = ['step_no']
    

main_app/forms.py
from django.forms import ModelForm
from .models import Instruction

class InstructionForm(ModelForm):
  class Meta:
    model = Instruction
    fields = ['step_no', 'description']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Recipe, Ingredient
from .forms import InstructionForm

# Home/Login Class Based View
class Home(LoginView):
  template_name = 'home.html'

# Recipes Class Based View
class RecipeCreate(LoginRequiredMixin, CreateView):
  model = Recipe
  fields = ['name', 'cuisine', 'description']
  success_url = '/recipes/'
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  
class RecipeUpdate(LoginRequiredMixin, UpdateView):
  model = Recipe
  fields = ['cuisine', 'description']

class RecipeDelete(LoginRequiredMixin, DeleteView):
  model = Recipe
  success_url = '/recipes/'

# Ingredients Class Based View
class IngredientCreate(LoginRequiredMixin, CreateView):
  model = Ingredient
  fields = '__all__'

class IngredientList(LoginRequiredMixin, ListView):
  model = Ingredient
  
class IngredientDetail(LoginRequiredMixin, DetailView):
  model = Ingredient

class IngredientUpdate(LoginRequiredMixin, UpdateView):
  model = Ingredient
  fields = ['name', 'category']
  
class IngredientDelete(LoginRequiredMixin, DeleteView):
  model = Ingredient
  success_url = '/ingredients/'

# Define the home view
# def home(request):
#   return render(request, 'home.html')

# Define the about view
def about(request):
  return render(request, 'about.html')

# Define the recipes views
@login_required
def recipes_index(request):
  recipes = Recipe.objects.filter(user=request.user)
  return render(request, 'recipes/index.html', { 'recipes': recipes })

@login_required
def recipes_detail(request, recipe_id):
  recipe = Recipe.objects.get(id=recipe_id)
  ingredients_recipe_doesnt_have = Ingredient.objects.exclude(id__in = recipe.ingredients.all().values_list('id'))
  instruction_form = InstructionForm()
  return render(request, 'recipes/detail.html', {'recipe': recipe, 'instruction_form': instruction_form, 'ingredients': ingredients_recipe_doesnt_have })

@login_required
def add_instruction(request, recipe_id):
  form = InstructionForm(request.POST)
  if(form.is_valid()):
    new_instruction = form.save(commit=False)
    new_instruction.recipe_id = recipe_id
    new_instruction.save()
  return redirect('recipes_detail', recipe_id=recipe_id)

@login_required
def assoc_ing(request, recipe_id, ingredient_id):
  Recipe.objects.get(id=recipe_id).ingredients.add(ingredient_id)
  return redirect('recipes_detail', recipe_id=recipe_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('recipes_index')
    else:
      error_message = 'Invalid sign up - try again'
      
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<section>
  <div>About</div>
</section>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Recipe Book</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'images/recipe.png' %}"
    />
    {% block head %} {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="{% url 'home' %}">
          <img
            style="width: 70%; margin-top: -8px"
            src="{% static 'images/recipebanner.png' %}"
            alt="The Cat Collector Logo"
          />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %} {% comment %}
          <li><a href="{% url 'about' %}">About</a></li>
          {% endcomment %}
          <li><a href="{% url 'recipes_index' %}">Recipes</a></li>
          <li><a href="{% url 'recipes_create' %}">New Recipe</a></li>
          <li><a href="{% url 'ingredients_index' %}">Ingredients</a></li>
          <li><a href="{% url 'ingredients_create' %}">Add Ingredient</a></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}" />
{% endblock %} {% block content %}

<section class="logo-container">
  <div class="cat-container">
    <img
      style="height: 30vh"
      src="{% static 'images/recipe.png' %}"
      alt="Recipe Collector"
    />
  </div>
  <img
    src="{% static 'images/recipebook.png' %}"
    alt="Text reads: Recipe Book"
  />
</section>

{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %} {% endblock %}

main_app/templates/main_app/ingredient_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="page-header">
  <h1>Delete Ingredient?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a href="{% url 'ingredients_detail' ingredient.id %}" class="btn secondary">
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/ingredient_detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/ingredients/ingredient-detail.css' %}"
/>
{% endblock %} {% block content %}

<div class="card">
  <div class="card-bg"></div>
  <div class="card-content">
    <h2>{{ ingredient.name }}</h2>
    <p>{{ ingredient.get_category_display }}</p>
  </div>
</div>
<a href="{% url 'ingredients_update' ingredient.id %}" class="btn warn">Edit</a>
<a href="{% url 'ingredients_delete' ingredient.id %}" class="btn danger"
  >Delete</a
>

{% endblock %}

main_app/templates/main_app/ingredient_form.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}
<div class="page-header">
  {% if object %}
  <h1>Edit {{object.name}}</h1>
  {% else %}
  <h1>Add an Ingredient</h1>
  {% endif %}
  <img src="{% static 'images/chef.png' %}" alt="A cat using a computer" />
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/ingredient_list.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/ingredients/ingredient-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>All Ingredients</h1>
  <img src="{% static 'images/ingredients4.png' %}" alt="A ball of string" />
  <img src="{% static 'images/ingredients5.png' %}" alt="A mouse" />
  <img src="{% static 'images/ingredients6.png' %}" alt="A scratching post" />
  <img src="{% static 'images/ingredients7.png' %}" alt="A fishy toy" />
</section>

<section class="card-container">
  {% for ingredient in ingredient_list %}
  <div class="card">
    <div class="card-bg"></div>
    <a href="{% url 'ingredients_detail' ingredient.id %}">
      <div class="card-content">
        <h2>{{ ingredient.name }}</h2>
        <p>{{ ingredient.get_category_display }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="page-header">
  <h1>Delete Recipe?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
<h2>Are you sure you want to delete {{ recipe.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a href="{% url 'recipes_detail' recipe.id %}" class="btn secondary">
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}

<div class="page-header">
  {% if recipe %}
  <h1>Edit {{ recipe.name }}</h1>
  {% else %}
  <h1>Add a Cat</h1>
  {% endif %}
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>

  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/recipes/detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/recipes/recipe-detail.css' %}"
/>
{% endblock %} {% block content %}

<section class="recipe-container">
  <div class="recipe-img">
    <img
      style="width: 100%"
      src="{% static 'images/meal.png' %}"
      alt="A skater boy recipe"
    />
  </div>
  <div class="recipe-details">
    <h1>{{ recipe.name }}</h1>
    <h2>A {{ recipe.cuisine }} cuisine</h2>
    <p>{{ recipe.description }}</p>
    <div class="recipe-actions">
      <a href="{% url 'recipes_update' recipe.id %}" class="btn warn">Edit</a>
      <a href="{% url 'recipes_delete' recipe.id %}" class="btn danger"
        >Delete</a
      >
    </div>
  </div>
</section>

<div class="instructions-ingredient-container">
  <section class="instructions">
    <div class="subsection-title">
      <h2>Instructions</h2>
      <img
        src="{% static 'images/ingredients1.png' %}"
        alt="An ice cream cone cat"
      />
      <img
        src="{% static 'images/ingredients2.png' %}"
        alt="A cat as onigiri"
      />
      <img
        src="{% static 'images/ingredients3.png' %}"
        alt="A kabob of kittens"
      />
    </div>
    {% if recipe.instruction_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>Step</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for instruction in recipe.instruction_set.all %}
        <tr>
          <td>{{instruction.step_no}}</td>
          <td>{{instruction.description}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="subsection-content">
      <p class="unfed">{{recipe.name}} has no instructions 😔</p>
    </div>
    {% endif %}
    <h3>Add an Instruction</h3>
    <form
      action="{% url 'add_instruction' recipe.id %}"
      method="post"
      class="subsection-content"
    >
      {% csrf_token %} {{ instruction_form.as_p }}
      <button type="submit" class="btn submit">Add Instruction</button>
    </form>
  </section>

  <section class="ingredients">
    <div class="subsection-title">
      <h2>Ingredients</h2>
      <img
        src="{% static 'images/ingredients4.png' %}"
        alt="A ball of string"
      />
      <img src="{% static 'images/ingredients5.png' %}" alt="A mouse" />
      <img
        src="{% static 'images/ingredients6.png' %}"
        alt="A fishy ingredient"
      />
    </div>
    <h3>{{ recipe.name }}'s Ingredients</h3>
    <div class="subsection-content">
      {% if recipe.ingredients.count %}
      <br />
      {% for ingredient in recipe.ingredients.all %}
      <div class="ingredient-container">
        <div class="color-block"></div>
        <a href="{% url 'ingredients_detail' ingredient.id %}">
          <p>{{ ingredient.name }}</p>
        </a>
      </div>
      {% endfor %}
      <br />
      {% else %}
      <p class="no-ingredients">
        {{recipe.name}} doesn't have any ingredients 😞
      </p>
      {% endif %}
    </div>
    <h3>Available Ingredients</h3>
    <div class="subsection-content">
      {% if ingredients.count %} {% for ingredient in ingredients.all %}
      <div class="ingredient-container">
        <div class="color-block"></div>
        <a href="{% url 'ingredients_detail' ingredient.id %}">
          <p>{{ ingredient.name }}</p>
        </a>
        <form
          action="{% url 'assoc_ing' recipe.id ingredient.id %}"
          method="post"
        >
          {% csrf_token %}
          <button type="submit" class="btn submit">Add Ingredient</button>
        </form>
      </div>
      {% endfor %} {% else %}
      <p class="all-ingredients">What in the absolute nasty are you making?</p>
      {% endif %}
    </div>
  </section>
</div>

{% endblock %}

main_app/templates/recipes/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/recipes/recipe-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Recipe List</h1>
  <img src="{% static 'images/recipe1.png' %}" alt="A cool cat" />
  <img src="{% static 'images/recipe2.png' %}" alt="A happy cat" />
  <img src="{% static 'images/recipe3.png' %}" alt="A cat in a teacup" />
  <img src="{% static 'images/recipe4.png' %}" alt="A cat in a box" />
</section>

<section class="card-container">
  {% for recipe in recipes %}
  <div class="card">
    <a href="{% url 'recipes_detail' recipe.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img
            style="width: 100%"
            src="{% static 'images/meal.png' %}"
            alt="A skater boy cat"
          />
        </div>
        <h2 class="card-title">{{ recipe.name }}</h2>

        <p>A {{ recipe.cuisine }} cuisine</p>

        <p><small>{{ recipe.description }}</small></p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/chef.png' %}" alt="A cat using a computer" />
</div>
{% if error_message %}
<p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}